// <auto-generated />
using System;
using Accrual.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accrual.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccrualDbContext))]
    [Migration("20260925163126_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accrual.Domain.Entities.AccrualSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema_type");

                    b.HasKey("Id")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SchemaType = "Linear"
                        });
                });

            modelBuilder.Entity("Accrual.Domain.Entities.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("BeneficiaryExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("beneficiary_external_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("SchemaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema_type");

                    b.HasKey("Id")
                        .HasName("pk_commissions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_commissions_created_at")
                        .HasFilter("paid_at IS NULL");

                    b.HasIndex("EventId", "BeneficiaryExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_commissions_event_id_beneficiary_external_id");

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("Accrual.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<decimal>("Profit")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("profit");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_external_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_events_external_id");

                    b.HasIndex("UserExternalId")
                        .HasDatabaseName("ix_events_user_external_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Accrual.Domain.Entities.Commission", b =>
                {
                    b.HasOne("Accrual.Domain.Entities.Event", null)
                        .WithMany("Commissions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commissions_events_event_id");
                });

            modelBuilder.Entity("Accrual.Domain.Entities.Event", b =>
                {
                    b.Navigation("Commissions");
                });
#pragma warning restore 612, 618
        }
    }
}
