// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wallets.Infrastructure.Persistence;

#nullable disable

namespace Wallets.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WalletsDbContext))]
    [Migration("20260925222735_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wallets.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_external_id");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("UserExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_user_external_id");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("Wallets.Domain.Entities.WalletCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_id");

                    b.Property<DateTimeOffset>("CreditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("credited_at");

                    b.Property<string>("EventExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_external_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_credits");

                    b.HasIndex("CommissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallet_credits_commission_id");

                    b.HasIndex("WalletId", "CreditedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_wallet_credits_wallet_id_credited_at_id");

                    b.ToTable("wallet_credits", (string)null);
                });

            modelBuilder.Entity("Wallets.Domain.Entities.WalletCredit", b =>
                {
                    b.HasOne("Wallets.Domain.Entities.Wallet", null)
                        .WithMany("Credits")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_credits_wallets_wallet_id");
                });

            modelBuilder.Entity("Wallets.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Credits");
                });
#pragma warning restore 612, 618
        }
    }
}
